//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AppUsage
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public Nullable<int> ModuleId { get; set; }
    public System.DateTime Date { get; set; }
    public string IP { get; set; }
    public int ResultCode { get; set; }
}

public partial class EDFModules
{
    public EDFModules()
    {
        this.UserModules = new HashSet<UserModules>();
        this.EDFUsage = new HashSet<EDFUsage>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<UserModules> UserModules { get; set; }
    public virtual ICollection<EDFUsage> EDFUsage { get; set; }
}

public partial class EDFUsage
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int ModuleId { get; set; }
    public int WorkTime { get; set; }
    public System.DateTime StartDate { get; set; }

    public virtual EDFModules EDFModules { get; set; }
    public virtual SCEUsers SCEUsers { get; set; }
}

public partial class SCEUsers
{
    public SCEUsers()
    {
        this.UserModules = new HashSet<UserModules>();
        this.EDFUsage = new HashSet<EDFUsage>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public string SCEAPIKey { get; set; }
    public int TimetableID { get; set; }
    public bool IsActive { get; set; }

    public virtual Timetables Timetables { get; set; }
    public virtual ICollection<UserModules> UserModules { get; set; }
    public virtual ICollection<EDFUsage> EDFUsage { get; set; }
}

public partial class Timetables
{
    public Timetables()
    {
        this.SCEUsers = new HashSet<SCEUsers>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public System.DateTime StartTime { get; set; }
    public System.DateTime EndTime { get; set; }
    public int MaxThreads { get; set; }
    public int MaxSeconds { get; set; }
    public int Delay { get; set; }

    public virtual ICollection<SCEUsers> SCEUsers { get; set; }
}

public partial class UserModules
{
    public int ModuleId { get; set; }
    public int UserId { get; set; }

    public virtual EDFModules EDFModules { get; set; }
    public virtual SCEUsers SCEUsers { get; set; }
}
